AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  UpdateDNS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::778501541840:role/UpdateDNSVPC'
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              source:
                - aws.cloudtrail
              detail:
                eventSource:
                  - cloudtrail.amazonaws.com
                eventName:
                  - RunInstances
                  - DeleteVpc
                  - CreateVpc
                  - TerminateInstances
        CloudWatchEvent2:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              source:
                - aws.ec2
              detail:
                eventSource:
                  - ec2.amazonaws.com
                eventName:
                  - CreateVpc
                  - DeleteVpc
        CloudWatchEvent3:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - EC2 Instance State-change Notification
              source:
                - aws.ec2
              detail:
                state:
                  - running
                  - terminated
